### ISSUE TITLE
Homebridge Not running

### ISSUE THREAD

**Issue by appleimperio** [jstrausd/homebridge-simple-wled#8]
After installing the latest update of the plugin it kill my homebridge. I remove the plugin and the configuration inthe config json but still having the same issue. Since im in docker i create a new container nothing same output in the logs.

[1/23/2021, 2:35:21 PM] Error loading accessory requested in your config.json at position 8

[1/23/2021, 2:35:22 PM] Error: The requested accessory 'WLED' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:345:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[1/23/2021, 2:35:22 PM] Got SIGTERM, shutting down Homebridge...

how can i fix this?

**Comment by jstrausd** [comment]
So you removed deinstalled the plugin and removed the configuration of the plugin from the config.json and you have still the same issue?
That's weird, it seems like your docker do not save this....

**Comment by giannimp** [comment]
same problem, uninstall and install but no wled dicovered

**Comment by jstrausd** [comment]
In the new version the plugin changed to a platform-plugin, so you have to move the configuration, to the platforms-sections instead of the the accessory section.

See the examples in the readme!

**Comment by appleimperio** [comment]
Got it. The problem is if you configured the WLED through config ui X it add both platform and accessory in the accessory section.
{
            "platform": "WLED",
            "name": "TV LED",
            "host": "192.168.1.181",
            "log": true,
            "effects": [
                "Rainbow Runner",
                "Sunrise",
                "Pacifica"
            ],
            "accessory": "WLED"
        }

You need to delete the "accessory":"WLED" in this case at the end and move the other part to the platform section.

I think the bug is in the way it add the instance through config ui. 

Thanks nice work it would be great if we turn off the effect it turn off the WLED.

**Comment by recom273** [comment]
> Thanks nice work it would be great if we turn off the effect it turn off the WLED.

I second this. 

Amongst other instances of WLED, I have a little single LED HAT in a tiny 3D printed cube - its a bit of fun really, it works with a presence switch - when the wife goes out the colour changes.

**Comment by jstrausd** [comment]
Ok, i will add an option for the config.json to turn off the WLED when turning off the effect....

**Comment by jstrausd** [comment]
@recom273 @appleimperio In the new version (1.2.1) I added the option to turn off the WLED when turning off the effect.
For further infos check the README.md
